version = 3
auto_upgrade = true
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = '╭─'
    template = ' {{ .Icon }} '
    foreground = '#1e1e2e'
    background = '#bac2de'
    type = 'os'


  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .Path }} '
    foreground = '#1e1e2e'
    powerline_symbol = ''
    background = '#94e2d5'
    type = 'path'

    [blocks.segments.properties]
      folder_icon = '…'
      folder_separator_icon = ' <transparent></> '
      max_depth = 3
      style = 'agnoster_short'

  [[blocks.segments]]
    style = 'diamond'
    trailing_diamond = ''
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <transparent></> <#1e1e2e> {{ .Working.String }}</>{{ end }}{{ if .Staging.Changed }} <transparent></> <#1e1e2e> {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }} <transparent></> <#1e1e2e> {{ .StashCount }}</>{{ end }} '
    foreground = '#1e1e2e'
    background = '#a6e3a1'
    type = 'git'
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}#f9e2af{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#eba0ac{{ end }}',
      '{{ if gt .Ahead 0 }}#cba6f7{{ end }}',
      '{{ if gt .Behind 0 }}#89b4fa{{ end }}'
    ]

    [blocks.segments.properties]
      branch_gone_icon = ''
      branch_icon = ' '
      branch_identical_icon = ''
      branch_max_length = 25
      fetch_stash_count = true
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .UserName }}@{{ .HostName }} '
    foreground = '#11111b'
    background = '#f38ba8'
    powerline_symbol = ''
    type = 'session'
    invert_powerline = true

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ .FormattedMs }} '
    foreground = '#cdd6f4'
    powerline_symbol = ''
    background = '#45475a'
    type = 'executiontime'
    invert_powerline = true

    [blocks.segments.properties]
      always_enabled = true
      style = 'austin'

  [[blocks.segments]]
    style = 'diamond'
    trailing_diamond = ''
    template = '  {{ .CurrentDate | date .Format }} '
    foreground = '#1e1e2e'
    background = '#fab387'
    type = 'time'
    invert_powerline = true

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '╰─ {{ if .Root }}#{{else}}${{end}}'
    foreground = '#bac2de'
    type = 'text'
