version = 2
final_space = true
console_title_template = '{{.UserName}}@{{.HostName}} in {{ .PWD }}'
auto_upgrade = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}}'
    background = '#003543'
    foreground = '#fff'

    [blocks.segments.properties]
      windows = ' '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ .Path }} '
    background = '#0087D8'
    foreground = '#003544'

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#f17c37{{ end }}']
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    background = '#d2ff5e'
    foreground = '#193549'

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'time'
    style = 'powerline'
    powerline_symbol = ''
    template = '<#fff>  </>{{ .CurrentDate | date .Format }} '
    background = '#003543'
    foreground = '#fff'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    trailing_diamond = ''
    template = '  {{ .FormattedMs }}⠀'
    background = '#83769c'
    foreground = '#ffffff'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    template = ' ⚡ '
    foreground = '#fff'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '🦄 '
    foreground = '#f1184c'
